### ISSUE TITLE
[Epic:Product] Products section in Trader-Profile as a new tab

### ISSUE THREAD

**Issue by christianaschoff** [lokalkauf/lokalkauf-frontend#152]
**TODO**:
- [x] Create product from trader profile (@patsimm)
- [x] Show all trader products in trader profile (@patsimm)
- [x] Update trader product (@patsimm)
- [x] Delete trader product (@patsimm)
- [x] Upload product images (@patsimm)

**Comment by christianaschoff** [comment]
Includes CRUD Operations on Product Items. 
Metadata should be part of that story as well

**Comment by christianaschoff** [comment]
@patsimm: will you focus on traders only or will enhance the customer-view also?
I think about replacing the carousel and I want to avoid merge issues.

**Comment by patsimm** [comment]
You can replace the carousel. I've not touched the customer side yet. Only moved the product-item component from customer to reusables but we didn't use that anyways.

**Comment by patsimm** [comment]
I am nearly done with the trader side. Only zhing that needs to be done is uploading the product images. I need to change the functions for that. Problem I have right now is that the max-trader-image-amount function also includes the product images. So the uploaded images are deleted right away. I don't have the time to fix that today but will do it soon. If someone has time to help out they can add the products to the customer side already. I did add a product service with a function to retrieve the products of a trader as well as a reusable product item. Should not be too much work to put a list of those into the trader-details page.
